/** Auto-generated by scripts/gen-build-config.mjs — do not edit by hand. */
export const DEFAULT_HUB_URL = "http://127.0.0.1:8765";
export const AUTO_STARTUP_ROTATE = true;
export const PRODUCT_DISPLAY_NAME = "Relay";
export const PRODUCT_TAGLINE = "账号切换助手（本地 Hub）";
export const SUPPORT_URL = "";
export const PURCHASE_URL = "";
export const ENABLE_OPS_TOOLS = false;
